language: node_js
node_js:
  - 10.1.0
script:
  - npm run test
before_install:
  - npm install -g npm@'>=6.0.1'
after_success:
  - ./node_modules/.bin/jscoverage lib lib-cov
  - MYPROJECT_COV=1 ./node_modules/.bin/mocha test -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
